name: Go Test and Lint

on:
  push:
    branches:
      - master
      - develop
      - feature/**

jobs:
  build-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.0

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.2

      - name: Lint
        run: make lint

      - name: Test
        run: make test